export const HISTORY_REQUEST_PENDING = "HISTORY_REQUEST_PENDING";
export const HISTORY_REQUEST_SUCCESS = "HISTORY_REQUEST_SUCCESS";
export const HISTORY_REQUEST_FAILURE = "HISTORY_REQUEST_FAILURE";

export const GET_HISTORY_REQUEST_SUCCESS = "GET_HISTORY_REQUEST_SUCCESS";
