export const CARD_REQUEST_PENDING = "CARD_REQUEST_PENDING";
export const CARD_REQUEST_FAILURE = "CARD_REQUEST_FAILURE";
export const CARD_REQUEST_SUCCESS = "CARD_REQUEST_SUCCESS";

export const CARD_POST_REQUEST_SUCCESS = "CARD_POST_REQUEST_SUCCESS";
export const CARD_PATCH_REQUEST_SUCCESS = "CARD_PATCH_REQUEST_SUCCESS";
export const CARD_DELETE_REQUEST_SUCCESS = "CARD_DELETE_REQUEST_SUCCESS";
